<img src="https://raw.githubusercontent.com/dark-teal-coder/dark-teal-coder/main/images/coder-no-background-000-128-128.png" alt="coder-black-background-000-128-128.png" width="100" height="100" align="right" style="margin:0px 5%">

<table style="width: 30%; border: none;">
	<tr>
    	<th style="text-align:left">GitHub:</th>
    	<td><a href="https://github.com/dark-teal-coder">@dark-teal-coder</a></td>
	</tr>
	<tr>
    	<th style="text-align:left">First Published Date:</th>
		<td>2022-05-12</td>
	</tr>
</table>


___


<table style="width: 45%; border: none; background-color: rgba(255, 255, 255, 0);">
	<tr>
		<th rowspan="2"><img src="https://raw.githubusercontent.com/dark-teal-coder/dark-teal-coder/main/images/coder-no-background-000-128-128.png" alt="coder-black-background-000-128-128.png" width="100" height="100" style="margin:0px 5%"></th>
		<th style="text-align:left">GitHub:</th>
		<td><a href="https://github.com/dark-teal-coder">@dark-teal-coder</a></td>
	</tr>
	<tr>
		<th style="text-align:left">First Published Date:</th>
		<td>2022-05-12</td>
	</tr>
</table>

___

<img src="https://raw.githubusercontent.com/dark-teal-coder/dark-teal-coder/main/images/coder-no-background-000-128-128.png" alt="coder-black-background-000-128-128.png" width="100" height="100" align="right" style="margin:0px 5%">
<p align="right">
GitHub: <a href="https://github.com/dark-teal-coder">@dark-teal-coder</a>
<br />
First Published Date: 2022-05-12
</p>

___

<img src="https://raw.githubusercontent.com/dark-teal-coder/dark-teal-coder/main/images/coder-no-background-000-128-128.png" alt="coder-black-background-000-128-128.png" width="100" height="100" align="right" style="margin: 0px 5%; vertical-align: middle;">
<div style='vertical-align: middle; display: inline;'>
<p align="right">
GitHub: <a href="https://github.com/dark-teal-coder">@dark-teal-coder</a>
<br />
First Published Date: 2022-05-12
</p>
</div>

___

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dark-teal-coder/code-snippets/blob/main/numpy_dot_product.ipynb)

# Dot Product Using NumPy

The performance of machine learning and deep learning models is highly dependent on the amount of data. A huge amount of data is needed in order to build such a robust and accurate model. As the amount of data grows, we need vectorized or matrix operations to make computations efficient. In Python, dot product can be realized using the NumPy library. 

> *Definition*: The **dot product** of two vectors is the sum of the products of elements with regards to position. 

Before entering into NumPy, it is essential to understand the basic dot product operations in matrix form in mathematical terms. See the illustration below. 

<!---
![Basic dot product rules](https://user-images.githubusercontent.com/95575665/167859350-834cbb79-823a-4a3e-95a8-f4cff593faf9.jpg)
--->
<p align="center">
<img src="https://user-images.githubusercontent.com/95575665/167859350-834cbb79-823a-4a3e-95a8-f4cff593faf9.jpg" alt="Basic dot product rules" width="480" height="360">
</p>

The following section will demonstrate how dot product can be done with `np.dot()` in NumPy. 

In [1]:
import numpy as np

## Vectors

Let's first create two simple vectors in the form of NumPy arrays and calculate their dot product.

In [2]:
## Create 2 numeric NumPy arrays to represent the two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
## Show the representation of the arrays
print(a, b, sep="\n")

[1 2 3]
[4 5 6]


In [4]:
## Dot product of the 2 arrays
np.dot(a, b)

32

The dot product is calculated as follows:

In [5]:
a[0]*b[0] + a[1]*b[1] + a[2]*b[2]

32

Since we multiply elements at the same positions, the two vectors must have same length in order to have a dot product. 

## Matrices 

In the field of data science, we mostly deal with matrices. A matrix contains row and column vectors combined in a structured way. Thus, multiplication of two matrices involves many dot product operations of vectors. 

Let's create two 2x2 matrices with NumPy and calculate their dot product.

In [6]:
## Create 2 numeric NumPy arrays to represent the two 2x2 matrices 
a_m2n2 = np.random.randint(10, size=(2, 2))
b_m2n2 = np.random.randint(10, size=(2, 2))

In [7]:
## Show the representation of the arrays
print(a_m2n2, b_m2n2, sep="\n")

[[9 4]
 [9 3]]
[[9 6]
 [9 3]]


A 2x2 matrix has 2 rows and 2 columns. Index of rows and columns start with 0. For instance, the first row of `a_m2n2` (row with index 0) is the array of `[9, 3]`. The first column of A is the array of `[9, 5]`. The element at first row and first column is `9`. We can access individual rows, columns, or elements with the following numpy syntax.

In [8]:
## First row 
a_m2n2[0]

array([9, 4])

In [9]:
## First column 
a_m2n2[:,0]

array([9, 9])

In [10]:
## First row, first column 
a_m2n2[0, 0]

9

The dot product operation follows the same orders as in mathematics. 

In [11]:
## Dot product of the 2 arrays
np.dot(a_m2n2, b_m2n2)

array([[117,  66],
       [108,  63]])

The requirement for matrix multiplication is that the number of columns of the first matrix must be equal to the number of rows of the second matrix.

Let's try to multiply a 3x2 matrix with a 2x3 matrix.

In [12]:
## Create 2 numeric NumPy arrays to represent the two 2x2 matrices 
a_m3n2 = np.random.randint(10, size=(3, 2))
b_m2n3 = np.random.randint(10, size=(2, 3))

In [13]:
## Show the representation of the arrays
print(a_m3n2, b_m2n3, sep="\n")

[[3 0]
 [8 6]
 [0 9]]
[[7 5 3]
 [0 7 0]]


In [14]:
## Dot product of the 2 arrays
np.dot(a_m3n2, b_m2n3)

array([[21, 15,  9],
       [56, 82, 24],
       [ 0, 63,  0]])

If the requirement for matrix multiplication is not met, `ValueError` will be raised. Consider the following example: 

In [15]:
## Both are 3x2 matrices
a_m4n3 = np.random.randint(10, size=(4, 3))
b_m4n3 = np.random.randint(10, size=(4, 3))
print(a_m4n3, b_m4n3, sep="\n")
try: 
	print(np.dot(a_m4n3, b_m4n3))
except ValueError: 
	print("Matrix multiplication fails.")

[[1 0 3]
 [1 4 9]
 [1 7 2]
 [0 5 0]]
[[9 7 3]
 [4 3 7]
 [9 7 2]
 [9 6 2]]
Matrix multiplication fails.


Error message: 

<p align="center">
<img src="https://user-images.githubusercontent.com/95575665/167895037-2db7def2-9bf9-4776-afbe-96ee5d7fcd4a.png" alt="Basic dot product rules" width="852" height="480">
</p>

We have covered basic dot production and matrix multiplication concepts above. These basic operations are the building blocks of complex machine learning and deep learning models. Thus, it is highly important to understand them.

For more information on `numpy.dot()`, see [the official documentation](https://numpy.org/doc/stable/reference/generated/numpy.dot.html).